sudo: required
services:
  - docker

before_install:
  - docker build -t cra_test -f Dockerfile.dev .

script:
  - docker run -e CI=true cra_test npm run test

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-434941416307"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY